In [32]:
import torch

FT = torch.FloatTensor

urbanData = torch.FloatTensor([[0.0000, 0.0000, 0.0000, 1.0000, 0.5000, 0.5000, 0.4990, 0.4990],[2.0000, 1.0000, 1.0000, 1.0000, 0.5000, 0.5000, 0.4990, 0.4990]])

cocoData = torch.FloatTensor([[ 0.0000, 58.0000,  0.4808,  0.4673,  0.3983,  0.5064],        [ 0.0000, 75.0000,  0.4988,  0.5616,  0.2600,  0.3051]])

labelsAndBox = urbanData

label_size = 3

correct_boxes, correct_labels = labelsAndBox[:, :label_size+1].t()

print(correct_boxes)
print(correct_labels)

boxes = labelsAndBox[:, 0]
labels = labelsAndBox[:, 1:label_size+1].t()[0]

print(boxes)
print(labels)


tensor([0., 0.])
tensor([58., 75.])
tensor([0., 0.])
tensor([58., 75.])
